CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "username" varchar,
  "first_name" varchar,
  "last_name" varchar,
  "email" varchar,
  "phone_num" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "admins" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "username" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "calculations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" integer,
  "cost" integer,
  "age" integer,
  "engine" integer,
  "volume" integer,
  "purpose" bool,
  "result_cost" integer
);

CREATE TABLE "calculation_params" (
  "id" SERIAL PRIMARY KEY,
  "param_name" VARCHAR(50) UNIQUE NOT NULL,
  "param_value" FLOAT NOT NULL,
  "description" VARCHAR(255),
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "calculations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
